<?php

use MediaWiki\Preferences\MultiUsernameFilter;
use MediaWiki\Registration\ExtensionRegistry;
use MediaWiki\ResourceLoader\Hook\ResourceLoaderRegisterModulesHook;
use MediaWiki\ResourceLoader\ResourceLoader;

class UserBoardHooks implements ResourceLoaderRegisterModulesHook {
	/**
	 * For the Echo extension.
	 *
	 * @param array[] &$notifications Echo notifications
	 * @param array[] &$notificationCategories Echo notification categories
	 * @param array[] &$icons Icon details
	 */
	public static function onBeforeCreateEchoEvent( array &$notifications, array &$notificationCategories, array &$icons ) {
		$notificationCategories['social-msg'] = [
			'priority' => 3,
			'tooltip' => 'echo-pref-tooltip-social-msg',
		];

		$notifications['social-msg-send'] = [
			'category' => 'social-msg',
			'group' => 'interactive',
			'presentation-model' => 'EchoUserBoardMessagePresentationModel',
			EchoAttributeManager::ATTR_LOCATORS => [
				[ 'EchoUserLocator::locateFromEventExtra', [ 'target' ] ],
			],

			'icon' => 'emailuser', // per discussion with Cody on 27 March 2016

			'bundle' => [ 'web' => true, 'email' => true ]
		];
	}

	/**
	 * Set bundle for message
	 *
	 * @param EchoEvent $event
	 * @param string &$bundleString
	 */
	public static function onEchoGetBundleRules( EchoEvent $event, &$bundleString ) {
		switch ( $event->getType() ) {
			case 'social-msg-send':
				$bundleString = 'social-msg-send';
				break;
		}
	}

	/**
	 * Show the list of blacklisted users (the people who can't send you user board messages) on
	 * Special:Preferences.
	 * Code and idea sporked from the Echo extension.
	 *
	 * @param User $user
	 * @param array &$preferences
	 */
	public static function onGetPreferences( $user, &$preferences ) {
		// If the Echo extension is available, bundle this preference option under its tab,
		// since the tab is labeled "Notifications", and although this preference does not
		// originate from Echo, it logically makes sense to group it under "Notifications".
		// But if we have no Echo, just dump it under the generic "Miscellaneous" tab.
		$isEchoAvailable = ExtensionRegistry::getInstance()->isLoaded( 'Echo' );
		$preferences['user-board-blacklist'] = [
			'type' => 'usersmultiselect',
			'label-message' => 'user-board-pref-notifications-blacklist',
			// Used i18n messages (generated by MW core): prefs-user-board (only when Echo is available)
			'section' => $isEchoAvailable ? 'echo/user-board' : 'misc',
			'filter' => MultiUsernameFilter::class,
		];
	}

	/**
	 * @inheritDoc
	 */
	public function onResourceLoaderRegisterModules( ResourceLoader $resourceLoader ): void {
		$dir = dirname( __DIR__ ) . '/resources';

		if ( ExtensionRegistry::getInstance()->isLoaded( 'WikiEditor' ) ) {
			$resourceLoader->register( [
				'ext.socialprofile.userboard.wikiEditor' => [
					'scripts' => 'js/WikiEditorIntegration.js',
					'dependencies' => 'ext.wikiEditor',
				],
			] );
		}
	}
}
